# Generated by Django 3.0.5 on 2020-04-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('artikelnr', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('artikelname', models.CharField(max_length=50)),
                ('preis', models.FloatField()),
                ('menge', models.IntegerField()),
            ],
        ),
    ]
