# Generated by Django 3.0.5 on 2020-05-08 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200501_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikel',
            old_name='artikelnr',
            new_name='artikelnummer',
        ),
    ]
