# Generated by Django 3.0.5 on 2020-05-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200508_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestellungen',
            old_name='stadt',
            new_name='ort',
        ),
        migrations.RenameField(
            model_name='bestellungen',
            old_name='hausnummer',
            new_name='plz',
        ),
        migrations.RemoveField(
            model_name='bestellungen',
            name='strasse',
        ),
        migrations.AddField(
            model_name='bestellungen',
            name='adresszusatz',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bestellungen',
            name='strasseHausnummer',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
